version: "2"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
     # - HTTP_USER= "${REDIS_USER:-admin}"
     # - HTTP_PASSWORD= "${REDIS_PASSWORD:-qwerty}"
      - HTTP_env= "${REDIS_USER}"
      - HTTP_env1= "${REDIS_PASSWORD}"
    ports:
      - 8889:8081
    depends_on:
      - redis
    
volumes:
  redis-data: