version: '3.4'

services:
  ksb_pumptest2_zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ksb_pumptest2_kafka:
    image: confluentinc/cp-kafka:5.3.1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ksb_pumptest2_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ksb_pumptest2_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "rawdata:1:1"
    depends_on:
      - ksb_pumptest2_zookeeper

  mockkafkaproducer:
    image: digitalunit4ksb/ksb_pumptest2_mockproducer:develop
    environment:
      KSB_kafkaUri: ksb_pumptest2_kafka:29092
      KSB_rawTopicName: rawdata
      KSB_rawMessagesPerSecond: 1
      KSB_rawSleeptime: 10
      KSB_daqKey: 1
    volumes:
      - C:/tmp/RawDataTemplate_a.json:/app/DataFiles/RawDataTemplate.json
    depends_on:
      - ksb_pumptest2_kafka
