version: '2'
services:
  birtscheduler_dev:    
    image: digitalunit4ksb/birtscheduler:develop
    ports:
      - "55725:8085"
    environment:
      - birtscheduler.corepoolsize=6
      - birtscheduler.maxpoolsize=30
      - birtscheduler.keepalivetime=150
      - birtscheduler.queuesize=150
      - birtscheduler.intervalperiod=60
    volumes:
      -  /mnt/camos/ksb:/app/camos/ksb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
