version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      #- xpack.security.enabled=false
    volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
      #- type: bind
      #  source: ./elasticsearch/config/elasticsearch.yml
      #  target: /usr/share/elasticsearch/config/elasticsearch.yml
      #  read_only: true
    ports:
      - 9200:9200
    restart: always
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.2
    user: root
    container_name: filebeat
    volumes:
      # needed to access all docker logs (read only) :
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
      # needed to access additional informations about containers
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ./filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      #- ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    networks:
      - elk
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://vndckr1c:9200"
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
      #- ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:

