server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://vndckr1c:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme

